spring:
  profiles:
    active:
    - dev
    
---
server: 
  port: 8888 
spring:
  profiles: dev
  application: 
    name: micro-service-cloud-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-dev.com:7001/eureka/   
      
---
server: 
  port: 8889 
spring:
  profiles: test
  application: 
    name: micro-service-cloud-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-test.com:7001/eureka/
 
